# Generated by Django 3.0.6 on 2020-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('github_username', models.CharField(max_length=30)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('avatar_url', models.CharField(max_length=100)),
                ('techs', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
